### ISSUE TITLE
Fix unresolved issues from original repo

### ISSUE THREAD

**Issue by stepanbenes** [stepanbenes/api-for-nopcommerce#1]
* Fix issues mentioned in https://github.com/SevenSpikes/api-plugin-for-nopcommerce/issues/223#issuecomment-650747655

* Port all fixes from https://github.com/MaximG1234/api-plugin-for-nopcommerce/commits/nopCommerce_4.10

**Comment by stepanbenes** [comment]
GroupBy issue resolved in #30

**Comment by D3bo** [comment]
@stepanbenes I think we can close this historical issue? unless you remember what elements needed to be handled.

**Comment by stepanbenes** [comment]
Yes, it can be closed. I fixed most of the mentioned issues, others were irrelevant. I kept it just for reference.
