### ISSUE TITLE
Getting 403 Forbidden error with the generated token

### ISSUE THREAD

**Issue by mahpour** [stepanbenes/api-for-nopcommerce#11]
I have generated the token from the `/token` endpoint using the following request: 

```
http://localhost:5000/token?username=xxx@x.com&password=yyy
```
The _decoded_ token includes the following data:
```
{
  "nbf": "1617831552",
  "exp": "1933191549",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": "xxx@x.com",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "20361ca2-605b-4f2b-8c5f-911c9db114c1",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "xxx@x.com"
}
```

 when I use the generated token in the `/api/swagger` or using postman to make requests I get 403 error. 

### Sample request
`http://localhost:5000/api/categories`
### Headers
```
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6I......
```

Am I missing any configurations in the admin area to make calls enable for my user?

**Comment by stepanbenes** [comment]
> Am I missing any configurations in the admin area to make calls enable for my user?
Yes. The user must have assigned `Api Users` role. I will add a note to the installation steps.

**Comment by mahpour** [comment]
OK, I figured out what I was missing. I wish you had some documentation explaining how this works. 

Under Admin area: Configuration > Access Control List :  There's a Role (called Permission) named `Api Users` which needs to be enabled per operation.
And then my user should be assigned to the `Api Users` role to be able to access that particular call. 

I hope other people find this useful in future.
