### ISSUE TITLE
where are  the “ApiBindings.NopApi.DTOs”  namespace and "ApiBindings.NopApi.NopApiClient" class?

### ISSUE THREAD

**Issue by hsb0307** [stepanbenes/api-for-nopcommerce#15]
Please, where are  the “ApiBindings.NopApi.DTOs”  namespace and "ApiBindings.NopApi.NopApiClient" class?

**Comment by stepanbenes** [comment]
These types are automatically generated using C# 9 source generator in project `ApiBindingsGenerator` from the file `nopapi.swagger.json`.

**Comment by snoperg** [comment]
I'm getting this error:

**Comment by stepanbenes** [comment]
closing as answered
