### ISSUE TITLE
Error on Orders with missing Shipping Address (Downloadable Products)

### ISSUE THREAD

**Issue by snoperg** [stepanbenes/api-for-nopcommerce#18]
I encountered error on running API https://localhost:5001/api/orders/customer/1 with no shipping address for downloadable products. Can you extend the API to include this list -> https://localhost:5001/customer/downloadableproducts?

**Comment by stepanbenes** [comment]
Yes, currently the shipping address is required even for downloadable products, I will fix that.

As for adding api to query downloadable products, I think it is more suitable for products controller. Something like `GET api/products?is_download=true`.

**Comment by snoperg** [comment]
Thanks a lot sir!

**Comment by stepanbenes** [comment]
Should be fixed now.
Just to clarify, the requirement of shipping address is controlled by `IsShipEnabled` property of the product entity (not `IsDownload`).
