### ISSUE TITLE
API for mobile app

### ISSUE THREAD

**Issue by mtugnoli** [stepanbenes/api-for-nopcommerce#19]
Hi,
I would like develope a my custom app (Xamarin Forms)
I it possible using this api to login from a android/iphone app ?

**Comment by stepanbenes** [comment]
Hi,
this repo contains api plugin for nopcommerce service running on a server. If you want to access this api from your Xamarin client app, you just call api endpoints using `HttpClient`. You can get inspiration in `ClientApp` project.

**Comment by stepanbenes** [comment]
Closing as answered.

**Comment by mtugnoli** [comment]
Hi again,

now that the api is working I have to dedicate myself to the app on xamarin.
Libraries are not recognized in the ClientApp app
using ApiBindings.NopApi;
using ApiBindings.NopApi.DTOs;

nopapi.swagger.json is included in the project, but I don't understand where the unrecognized classes are.

**Comment by stepanbenes** [comment]
These classes are automatically generated by C# 9 source generator in ApiBinding project. If you do not want to include dependency to this project, just copy the generated classes to you project.

**Comment by mtugnoli** [comment]
Sorry but I don't understand...
where are the classes that define NopApiClient,TokenRequest,ShoppingCartItemDtoDelta etc etc ?

**Comment by stepanbenes** [comment]
They are just in memory, they are generated from the swagger json file during the build.
