### ISSUE TITLE
API and Swagger

### ISSUE THREAD

**Issue by mtugnoli** [stepanbenes/api-for-nopcommerce#20]
I just testing this plugin with swagger, but seem something wrong...
my steps :

1) press authorize button, and set "Bearer JWT" password 
2) test Token with  "https://localhost:44369/token", and api return correctly 
	_{
	  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOiIxNjIyMTE0NzY5IiwiZXhwIjoiMTYyMjM3Mzk2OSIsIkN1c3RvbWVySWQiOiI0IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJiNjVkZjNiOC01YjU2LTQ1OWYtOWZmYy1kZDhlZDQwNTQ5MzUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1bmtub3dAbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidW5rbm93QG1haWwuY29tIn0.xjwE74luvb5cdryTGqq_ExqbeINpCuGEG81TbY7tkPo",
	  "token_type": "Bearer",
	  "created_at_utc": "2021-05-27T11:26:09.9818257Z",
	  "expires_at_utc": "2021-05-30T11:26:09.9818257Z",
	  "username": "unknow@mail.com",
	  "customer_id": 4,
	  "customer_guid": "b65df3b8-5b56-459f-9ffc-dd8ed4054935"
	}_

3) try another api function like "https://localhost:44369/api/products/count", but return a Bearer error

_content-security-policy: default-src 'self'; connect-src *; font-src * data:; frame-src *; img-src * data:; media-src *; object-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline';  date: Thu,27 May 2021 11:30:14 GMT  permissions-policy: accelerometer=(),camera=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),payment=*,usb=()  referrer-policy: same-origin  server: Microsoft-IIS/10.0  strict-transport-security: max-age=31536000; includeSubDomains  www-authenticate: Bearer error="invalid_token"  x-content-type-options: nosniff  x-firefox-spdy: h2  x-frame-options: SAMEORIGIN  x-sourcefiles: =?UTF-8?B?RDpcU09VUkNFU1xXb3Jrc1xOb3BGcmFtZXdvcmsuZUxlYXJuaW5nIDQuNFxQcmVzZW50YXRpb25cTm9wLldlYlxhcGlccHJvZHVjdHNcY291bnQ=?=  x-xss-protection: 1; mode=block_

**Comment by stepanbenes** [comment]
Can you share the code for api call? Did you attach the token as request header?

**Comment by mtugnoli** [comment]
How attach the token ?
I'm not very good with swaggers, this is Request URL 

`https://localhost:44369/api/products/count?is_download=true&created_at_min=2021-05-27T11%3A19%3A36.696Z&created_at_max=2021-05-27T11%3A19%3A36.696Z&updated_at_min=2021-05-27T11%3A19%3A36.696Z&updated_at_max=2021-05-27T11%3A19%3A36.696Z&published_status=true&vendor_name=string&category_id=0`

**Comment by stepanbenes** [comment]
Each request must contain the `Authorization` header with the value `Bearer <access_token>`.

For experimenting with the api, you can use swagger ui at `https://localhost:<port>/api/swagger` and there is the Authorize button at the top where you insert `Bearer <access_token>` value.

**Comment by stepanbenes** [comment]
There is a misunderstanding maybe. The "Bearer JWT" is not a password, you must replace the `JWT` (Json Web Token) with a accees token returned by `/token` api.

**Comment by mtugnoli** [comment]
Thank You !

Now run...

**Comment by stepanbenes** [comment]
You are welcome. Glad I could help.

**Comment by mtugnoli** [comment]
Please last question....
On my local PC run ok,
I've tried to publish on my hosting , and page /api/swagger return page not found
of course the plugin was loaded and set values on facebug plugin (like on my local pc)

Any idea ?

**Comment by stepanbenes** [comment]
Are you on https? I am experiencing the same problem as you when I test on http.

**Comment by stepanbenes** [comment]
Sorry, my bad. Swagger UI is not supposed to work in production environment, only in development. That is the actual reason why it does not work. See https://github.com/stepanbenes/api-for-nopcommerce/blob/865e175d8ed4b3bc11848b06296ec54801538a6b/Nop.Plugin.Api/Infrastructure/ApiStartup.cs#L193

I don't know if it is desired behavior. If you want it to work even for deployed apps, please open new issue.

**Comment by stepanbenes** [comment]
Fixed in 4b2bc52a6ac0c395f0e5d49bac7640b413483204. Swagger UI allowed for Production environment.
