### ISSUE TITLE
api products error: Value cannot be null. (Parameter 'value')

### ISSUE THREAD

**Issue by semt20** [stepanbenes/api-for-nopcommerce#21]
Hello everyone. I can get categories without problem via api. But when i try to get products i get an error.(First i called with default swagger parameters and then i set it null like i used in to get categories)

{
    "error": "Value cannot be null. (Parameter 'value')"
}
![nopcc](https://user-images.githubusercontent.com/17011652/120107099-557dcf00-c168-11eb-9025-3c9e96765900.png)

**Comment by stepanbenes** [comment]
Hi, method parameters decorated with `FromQueryJson` attribute must be url encoded json string. Therefore the default swagger parameters will fail. Try `"{}"` instead (including quotes).

**Comment by Tripplefix** [comment]
Hi @stepanbenes 
I have just encountered the same issue. It works if I wrap the parameters in double quotes:
`"{\"fields\": \"Name\"}"`

Is there a reason for that? Some endpoints like Category don't require this approach.

**Comment by stepanbenes** [comment]
Hi @Tripplefix, there is no reason for that. You are right, the query parameters should be unified across all controllers. I added `FromQueryJson` parameters type to allow easier implementation of api client source generator (project `ApiBindingsGenerator`). I will remove query json parameters as soon as I will come with a suitable implementation.

**Comment by stepanbenes** [comment]
Related to https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/66

**Comment by stepanbenes** [comment]
Fixed in 561bfc87cbf0612466d9959f2af8a212949a4a9b. All `FromQueryJson` parameters were removed. Swagger UI should work correctly now.
