### ISSUE TITLE
nop commerce working azure  plugin not working

### ISSUE THREAD

**Issue by engingor** [stepanbenes/api-for-nopcommerce#22]
nopcommerce api plugin installed 
https://dev.qpsecret.com/api/swagger not page found
localhost test its working

**Comment by stepanbenes** [comment]
Fixed in 4b2bc52a6ac0c395f0e5d49bac7640b413483204. Swagger UI allowed for Production environment.

**Comment by stepanbenes** [comment]
Closing as fixed.
