### ISSUE TITLE
GET customers ALL not working

### ISSUE THREAD

**Issue by engingor** [stepanbenes/api-for-nopcommerce#26]
{
    "errors": {
        "internal_server_error": [
            "please, contact the store owner"
        ]
    }
}

**Comment by stepanbenes** [comment]
Related to #3

**Comment by semt20** [comment]
Iam getting same error, Alternatively when i try to use api:  /api/customers/search on swagger Iam getting below error (pictures is at the bottom)
`{
  "error": "You should explicitly specify selected fields for server-side GroupBy() call or add AsEnumerable() call before GroupBy() to perform client-side grouping.\nSet Configuration.Linq.GuardGrouping = false to disable this check.\nAdditionally this guard exception can be disabled by extension GroupBy(...).DisableGuard().\nNOTE! By disabling this guard you accept additional Database Connection(s) to the server for processing such requests."
}`
![nopcommerce22](https://user-images.githubusercontent.com/17011652/121778773-240df600-cba1-11eb-9e39-89d71396bbc1.png)

**Comment by stepanbenes** [comment]
Fixed in #30
