### ISSUE TITLE
Call api with HttpClient

### ISSUE THREAD

**Issue by mtugnoli** [stepanbenes/api-for-nopcommerce#29]
How authorize (like swagger button) with HttpClient calling ?
Have a sample ?

**Comment by stepanbenes** [comment]
See `ClientApp` project.

https://github.com/stepanbenes/api-for-nopcommerce/blob/b552042818e2647e6d723d64500fec9c7c8ad6c3/ClientApp/Program.cs#L31

**Comment by stepanbenes** [comment]
then set access token returned in tokenResponse as Authorization header in each http request

**Comment by mtugnoli** [comment]
Yes, in my local PC now is run !
I tried to run it in production on my provider as well, but it gives me an error :

_? response
{StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Accept-Ranges: none
  Connection: keep-alive
  Content-Security-Policy: default-src 'self'; connect-src *; font-src * data:; frame-src *; img-src * data:; media-src *; object-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline';
  Date: Mon, 14 Jun 2021 09:52:36 GMT
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=*, usb=()
  Referrer-Policy: same-origin
  Server: Microsoft-IIS/10.0
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Via: HTTP/1.1 forward.http.proxy:3128
  X-Android-Received-Millis: 1623664334620
  X-Android-Response-Source: NETWORK 403
  X-Android-Selected-Protocol: http/1.1
  X-Android-Sent-Millis: 1623664334561
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  X-Powered-By-Plesk: PleskWin
  X-XSS-Protection: 1; mode=block
  Content-Length: 0
}}
    base: {System.Net.Http.HttpResponseMessage}
    RequestNeedsAuthorization: false
    RequestedAuthentication: (null)
>_
