### ISSUE TITLE
Bad request error when running ClientApp

### ISSUE THREAD

**Issue by matthewha** [stepanbenes/api-for-nopcommerce#31]
Hi,

When running the client app, there's a bad request error when creating a shopping cart item.

I'm also having a similar issue with swagger by getting forbidden errors when requesting the shopping cart, even with the bearer token and correct customer id for the logged in user, although admin access is fine.

Cheers

**Comment by stepanbenes** [comment]
> When running the client app, there's a bad request error when creating a shopping cart item.

Does the product id you are referencing exist in your database? Can you share the error message in the exception?
 
> I'm also having a similar issue with swagger by getting forbidden errors when requesting the shopping cart, even with the bearer token and correct customer id for the logged in user, although admin access is fine.

The user probably does not have sufficient permissions. Either he does not own the shopping cart or he is not in admin role. See: https://github.com/stepanbenes/api-for-nopcommerce/blob/b18c876d9aa6c2c0a7d5de18794d7b64f6120da4/Nop.Plugin.Api/Controllers/ShoppingCartItemsController.cs#L323

**Comment by matthewha** [comment]
Thanks for the fast response!

For the first one, I'm just running the client app without any changes so you should be able to replicate straight from the repo. It's a clean nopcommerce 4.40.3 install too.

For the second, I'm using a bearer token/customer id that matches but there's no shopping cart created - I would have thought it would return an empty shopping cart? That's why I thought it may be related to the first regarding permissions (I was going to see if it was me on the first point by running the client app and seeing how that worked).

**Comment by matthewha** [comment]
After a bit of fiddling, it's because product id 1 from the sample data has attributes that need to be set. Not sure if you want to update the client app to check whether there are required attributes and keep this issue open or close it.
Example working request:
{
  "shopping_cart_item": {
    "quantity": 1,
    "shopping_cart_type": "ShoppingCart",
    "product_id": 1,
    "customer_id": 16,
    "id": 0,
    "product_attributes": [
        {
          "value": 2,
          "id": 1
        },
        {
          "value": 3,
          "id": 2
        },
        {
          "value": 6,
          "id": 3
        },
        {
          "value": 8,
          "id": 4
        },
        {
          "value": 10,
          "id": 5
        }
      ]
  }
}

**Comment by stepanbenes** [comment]
Thanks for feedback. ClientApp was updated to reference newly added product instead of depending on an existing one. See dd96a801143d71b52798c7010f0725f8a2e866b7
