### ISSUE TITLE
Swagger api always send 403 error

### ISSUE THREAD

**Issue by Ahmed-Hady** [stepanbenes/api-for-nopcommerce#34]
Swagger api always send 403 error
**below the step i did**
1- installed the plugin using the way described in github repo readme file
2- solved  the facebook plugin issue using the mentioned-in-readme workaround
3- assigned api user permission to admin user
4- login and got a token
5- authenticate using "Authorize" button in swagger ui
6- tried to get Categories using /api/categories api

then i got 403 error at all parameter combinations  i did..
also tried some other apis like categories count api and custom role api which have no parameters

please can u tell me how to fix this issue?

**Comment by stepanbenes** [comment]
403 error indicates that the current user does not have sufficient permissions. The user must be at least in `Api Users` role AND also the roles which are assigned to the user must have permissions set in Access control list (go to `Administration/Configuration/Access control list` menu).

**Comment by Ahmed-Hady** [comment]
Thanks for speed replying .. i assigned the role and also navigated to the Access Control list and assigned all available permissions in the list but still 403

**Comment by Ahmed-Hady** [comment]
Thanks for speed replying .. it works now

**Comment by stepanbenes** [comment]
Can I ask what was the problem?

**Comment by Ahmed-Hady** [comment]
the problem was the permissions in access control were not set .. and also after setting there was a problem in iis express .. so it works when i set the permissions and restart the iis
