### ISSUE TITLE
thanks a lots ,how to used multiple language

### ISSUE THREAD

**Issue by lankii** [stepanbenes/api-for-nopcommerce#37]
How to add products in multiple languages

**Comment by lankii** [comment]
this multiple lang table,:I try to read the net code but I don't understand it at all

CREATE TABLE `LocalizedProperty` (
  `Id` int(11) NOT NULL,
  `LocaleKeyGroup` varchar(400) NOT NULL,
  `LocaleKey` varchar(400) NOT NULL,
  `LocaleValue` longtext NOT NULL,
  `LanguageId` int(11) NOT NULL,
  `EntityId` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

seo url table:

CREATE TABLE `UrlRecord` (
  `Id` int(11) NOT NULL,
  `EntityName` varchar(400) NOT NULL,
  `Slug` varchar(400) NOT NULL,
  `EntityId` int(11) NOT NULL,
  `IsActive` tinyint(1) NOT NULL,
  `LanguageId` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by lankii** [comment]
With this multi-language architecture, His name and description in a language, a detailed description requires three records to be read.I am worried that when there are tens of thousands of products, reading the multi-language field table back and forth will cause the website to be very stuck.

**Comment by stepanbenes** [comment]
Currently there is no way to add product in multiple languages using api. However, you can localize product in nopCommerce administration page. Then you can set customer language calling the _SetCurrentLanguage_ action method in _Languages_ controller (`api/languages/current`) and then you can read products with localized name and description properties.

**Comment by stepanbenes** [comment]
@lankii Did you manage to resolve the problem? If yes, please close this issue.

**Comment by lankii** [comment]
ok thanks.

I changed the official importexport.cs to support 6 languages and upload 8 main pictures at a time, random products of the same category, relates, and crosssell, just add the official excel import format to my modified You can upload it directly, just replace nop.service.dll, contact me if you need it, it’s best to exchange the themes template, I tried to modify it, but the template mechanism was really too cumbersome, and I gave up nopcomerice
