### ISSUE TITLE
using ApiBindings.NopApı.DTOs;

### ISSUE THREAD

**Issue by yamanbas** [stepanbenes/api-for-nopcommerce#38]
Hi, 
I could use this class as "ApiBindings.NopApı.DTOs" not ApiBindings.NopApi.DTOs;
and also still errors as the picture below.
![image](https://user-images.githubusercontent.com/15645904/130504883-8dd8c8b0-97ef-4525-8c6a-1c191a1eecdf.png)
How can I fix them ?

**Comment by stepanbenes** [comment]
Hi,
I don't understand. You are using `NopApı` with dotless `i`. Why? It is different unicode character. C# does not recognize the type because it is in a different namespace.

**Comment by yamanbas** [comment]
Hi,
Also I didn't understand  :) but I could resolve the problems by change this and also change some of the  lines as below.
May be it happened because of the my  computer international settings are for  Turkey

			INopApıClient  nopApiClient = new NopApıClient(httpClient);


						Customerİd = tokenResponse?.Customerİd,
						Productİd = newProduct?.İd,

**Comment by stepanbenes** [comment]
Interesting. This is a C# issue. It is magic for me how it is dealing with these special turkish characters. Sometimes it works, sometimes not. I recommend you to use english language settings when doing programming. I also do not use Czech symbols (as I am from Czech republic) for variable names for the same reasons.

**Comment by stepanbenes** [comment]
Did it help? If yes, please close the issue.

**Comment by yamanbas** [comment]
Hi ,

I need to arrange windows form  client project. But I cannot add reference apibindingsgenerator project.  When I add dll as reference no ApiBindings namespace. How can I achieve this?
