### ISSUE TITLE
Update the plugin.json file.

### ISSUE THREAD

**Issue by wileyknight** [stepanbenes/api-for-nopcommerce#41]
On latest build for nopCommerce the version number is 4.50. Will want to update the plugin.json to get this to show up on the newest build.

from:
```
{
  "Group": "Api",
  "FriendlyName": "Api plugin",
  "SystemName": "Nop.Plugin.Api",
  "Version": "4.4.0",
  "SupportedVersions": [ "4.40" ],
  "Author": "Nop-Templates team",
  "DisplayOrder": -1,
  "FileName": "Nop.Plugin.Api.dll",
  "Description": "This plugin is Restfull API for nopCommerce"
}
```

to:

```
{
  "Group": "Api",
  "FriendlyName": "Api plugin",
  "SystemName": "Nop.Plugin.Api",
  "Version": "4.4.0",
  "SupportedVersions": [ "4.50" ],
  "Author": "Nop-Templates team",
  "DisplayOrder": -1,
  "FileName": "Nop.Plugin.Api.dll",
  "Description": "This plugin is Restfull API for nopCommerce"
}
```

**Comment by stepanbenes** [comment]
Did you test the plugin works with the latest version of nopcommerce?

**Comment by wileyknight** [comment]
I am having a problem. I can't tell yet. It's loading and I am able to get a swagger page but the authentication isn't returning any results. I opened an issue for it.

**Comment by wileyknight** [comment]
I get the same problem running the api on version 4.40 it seems like its running but all of the api endpoints wont work because of authentication.

**Comment by D3bo** [comment]
version 4.50 is supported since #56
