### ISSUE TITLE
401	Error: Unauthorized

### ISSUE THREAD

**Issue by wileyknight** [stepanbenes/api-for-nopcommerce#42]
I keep getting a 401 Error: Unauthorized trying to bring up any api endpoint. I've added myself (Admin) as an api user and guest to the customer roles. Tried limiting the access to this website. Also tried without those. I've disabled both ACL rules and limit to stores.

I did change the supporting version number from 4.40 to 4.50 to get it to work but wouldn't figure that to cause any problems.

I have clicked on the Authorize button and in the value I added: Bearer JWT

Still no results.

**Comment by D3bo** [comment]
Not relevant anymore since the release of version 4.5.
