### ISSUE TITLE
create or update category not effect to the UrlRecord Table

### ISSUE THREAD

**Issue by yamanbas** [stepanbenes/api-for-nopcommerce#44]
After create or update categories the menu links are not working because of the UrlRecord table is not updated. Need to open category and  save by the admin page of nopcommerce.

**Comment by stepanbenes** [comment]
Good catch. Thanks. I did not know about the `UrlRecord`. However, is this desirable behavior? Wouldn't make sense to update `UrlRecord` using api instead?

**Comment by yamanbas** [comment]
actually UrlRecord is been update by create or update products. but no with create or update Categories. If a category insert by nopApiClient.CreateCategory it can show at page but dysfunctional.  UrlRecord can be update by sql as 
"insert into UrlRecord (EntityName,Slug,EntityId,IsActive,LanguageId) select 'Category',Name,Id,1,0 from Category" After this restart required.
also it may be update with Nop.Services.Seo.IUrlRecordService.cs functions as described here (I didn't check) : https://www.nopcommerce.com/en/boards/topic/27541/urlrecord-when-deleting-cateory-or-product
I will try to debug and fix plugin later

**Comment by stepanbenes** [comment]
@yamanbas Thank you!

**Comment by yamanbas** [comment]
Hi,
when I checked I saw that it's related to the SeName property of the CategoryDto
If it's not null UrlRecord table is updating and by the way Categories are work
