### ISSUE TITLE
installation problem on 4.40.4

### ISSUE THREAD

**Issue by muhammedtas** [stepanbenes/api-for-nopcommerce#49]
Hello. 

I tried to install this plugin as you documented. 

It seems like installable on admin panel. I activated it. 

But then application started to crash on startup, by saying someting like "System.IO.FİleNotFoundException" for Microsoft.IdentityModel.Tokens Version 5.5.0.0, and also for Microsoft.IdentityModel.Logging dlls. 

I've investigated the problem a little bit  and I saw that, in build time, some of the dll's in your plugin was not installed to  Nop.Web/Plugins/bin folder. Then when NopEngine.cs tries inject plugin's interfaces to application via reflection, it failes to resolve dependencies.

On top of that my current nopcommerce version has Microsoft.IdentityModels.Tokens version as 5.2.4.0 but this plugin has 5.5.0.0

Do you have any suggestion for my problem?

**Comment by mtugnoli** [comment]
I have a similar problem, in my pc is installed to Nop.Web/Plugins/bin folder
but program stay in program.cs -> await host.StartAsync();

**Comment by muhammedtas** [comment]
@mtugnoli it may be the same problem. Because what StartAsnyc() class does is to call ConfigureService methods and the others. For my case the breaking line is => (NopEngine.cs line : 152 - instance.ConfigureServices(services, configuration);) 

 If I am not wrong the missing dlls are => Microsoft.IdentityModel.Tokens and Microsoft.IdentityMode.Logging version 5.5.5.0 

Some how application is not installing these dlls to Plugin/bin folder. Because PluginManager.cs class decides to not install these dlls to target folder, because of its behaviour that I am not aware of for now. 

I got this point. One way or another I can fix this point. 

Then, I tried to manually copy the dlls that plugin wants to Plugin bin files, just after  the other dlls are installed by stopping execution with breakpoints. 

It allows me to continue breaking line. 

But now, application confuses to initialize related classses because it wants both version 5.5.0.0 and 5.2.4.0 in the same folder. 

So I guess the possible solution is to drop plugin dll's version to 5.2.4 for my case. Then investigate how to install these dlls to Plugin/bin folder programatically. 

Does it make sense to you?

**Comment by mtugnoli** [comment]
@muhammedtas in my case is same, after compiled the plugin all dll seem in the target folder, but after installed (from btutton on admin section), i restart the app and no one error, but debug remain in await host.StartAsync();
and all seem locked

**Comment by muhammedtas** [comment]
@mtugnoli 
Did you try installing this plugin, by copying it to directly NopCommerce/Plugins folder? 

What I did after fixing my problem is that, I copied api pluging to where the others are in. Then update its .csproj file. Then build it. Now its running quite stable. 
<img width="206" alt="image" src="https://user-images.githubusercontent.com/28702421/144175331-bb244576-dc0a-4b35-894e-9a25c646531a.png">

**Comment by HeroSpha** [comment]
@muhammedtas im trying to follow the documentation i can see the API is generated under Nop.Web plugins but its not available under admin local plugins. Can you help what might be the problem?

**Comment by jacobuslee** [comment]
I installed the API plugin.
May I ask where I can obtain API Token?
Thanks

**Comment by stepanbenes** [comment]
@jacobuslee use `POST` request to `/token` endpoint. See swagger UI or `/Nop.Plugin.Api/Controllers/TokenController.cs`.

**Comment by HeroSpha** [comment]
Good day, i managed to generate the files but they dont contain csproj file. Is my folder contents correct?

![image](https://user-images.githubusercontent.com/18328296/158082579-86c2b265-3361-4462-8272-c0efa6cfeb25.png)

**Comment by HeroSpha** [comment]
Actually im not seeing any installed pluggin in my admin local plugins

**Comment by jacobuslee** [comment]
I installed "api-for-nopcommerce 4.40.4" in the past, and now I want to download it again and read the instruction. Is "api-for-nopcommerce 4.40.4" no longer available now?

**Comment by jacobuslee** [comment]
Do I also need to add "Api Users" Role to User in  "api-for-nopcommerce 4.40.4" because I cannot find  "Api Users" Role option in the API Plugin.

**Comment by jacobuslee** [comment]
The token can be obtain, so the traffic is fine.
However, API calls are forbidden. 
Does anyone know what the issue is?

**Comment by jacobuslee** [comment]
I found the solution. Thanks

**Comment by D3bo** [comment]
> I found the solution. Thanks

**Comment by UAsoftwaredeveloper** [comment]
There is some of issues are present according to 4.40,
StandardPermission
