### ISSUE TITLE
Rebuild error

### ISSUE THREAD

**Issue by HeroSpha** [stepanbenes/api-for-nopcommerce#53]
Good day, 

I tried to rebuild api-for-nopcommerce following your documentation, but I'm getting 3 errors .

1. DataSettingsManager' does not contain a definition for 'IsDatabaseInstalledAsync'
2. ILocalizationService' does not contain a definition for 'AddLocaleResourceAsync
3. IServiceCollection' does not contain a definition for 'AddConfig' and no accessible extension method 'AddConfig' accepting a first argument of type 'IServiceCollection'.

I did look at the interface **ILocalizationService** there is no method called **AddLocaleResourceAsync**

**Comment by HeroSpha** [comment]
![image](https://user-images.githubusercontent.com/18328296/144725638-8df0c132-008a-4d10-9cb6-443f9a412c3c.png)

**Comment by D3bo** [comment]
This issue refer to the previus version of the api e di nopCommerce, so this issue is not relevant anymore.
