### ISSUE TITLE
How can I get token?

### ISSUE THREAD

**Issue by EstebanDev0411** [stepanbenes/api-for-nopcommerce#54]
I have installed api-nopcommerce-plugin following your description and I found the swagger api.
But to authorize button, it need to get token.
How can I take?
Please hope for your help.

**Comment by D3bo** [comment]
make a POST request to the /token endpoint.
![image](https://user-images.githubusercontent.com/15902670/150798366-869f38b5-e9d4-4c94-ab62-173588dace4d.png)

**Comment by johnsoncae1005** [comment]
Thanks a lot.
It works.
One more question, please!
Which api shoud I use to login, register with nopcommerce backend?

**Comment by D3bo** [comment]
Answered.
