### ISSUE TITLE
Update nopcommerce 4.5

### ISSUE THREAD

**Issue by D3bo** [stepanbenes/api-for-nopcommerce#55]
Is there any plan to upgrade the project to the new release of nopcommerce and .net 6?

**Comment by brandon71** [comment]
We would also be interested in un update to 4.50. 

We have done some work trying to make the api work for 4.50. One thing we noticed was that Nop changed the Implemenation of INopStartup. The Order property was 0 for version 4.40. (public int Order => 0) Version 4.50 has a property value of 2000. This API Plugin has the order property is set to 1. This would not work for us. We changed the value to 101 and it appears to be working. I just wanted to identify this issue hoping it may help if this plugin is upgraded to support 4.50.

**Comment by D3bo** [comment]
#56 this solution is working for me. @brandon71 for this issue I split the implementation of INopStartup (ApiStartup and DependencyRegister), with minimal changes to the structure of the previous version of the API.

**Comment by D3bo** [comment]
I don't know if @stepanbenes still support this project. However, i create a pull request that work with the latest stable release of nop.

**Comment by Samadmehmood** [comment]
if you have your own repo please drop a link.

**Comment by D3bo** [comment]
#56

**Comment by stepanbenes** [comment]
@D3bo Sorry, I did not have time recently. I merged your PR. Thank you for your work.
