### ISSUE TITLE
401 Error 

### ISSUE THREAD

**Issue by osmangunen51** [stepanbenes/api-for-nopcommerce#58]
hello
I am getting an error like 
How can I fix
 content-security-policy: default-src 'self'; connect-src *; font-src * data:; frame-src *; img-src * data:; media-src *; object-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline'; 
 date: Sun,06 Feb 2022 04:33:46 GMT 
 permissions-policy: accelerometer=(),camera=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),payment=*,usb=() 
 referrer-policy: same-origin 
 server: Microsoft-IIS/10.0 
 strict-transport-security: max-age=31536000; includeSubDomains 
 www-authenticate: Bearer 
 x-content-type-options: nosniff 
 x-frame-options: SAMEORIGIN 
 x-sourcefiles: =?UTF-8?B?QzpcVXNlcnNcVHVhbm5hXFNvdXJjZVxSZXBvc1xucGNcUHJlc2VudGF0aW9uXE5vcC5XZWJcYXBpXGxhbmd1YWdlcw==?= 
 x-xss-protection: 1; mode=block

**Comment by aedballs** [comment]
I had this same issue, but was able to resolve it by ensuring "Bearer" was input before the token in the authorize pop up. You'll also need to go into Configuration -> Access Control List and grant your API User account the necessary permissions. For instance, the customers API requires the Admin area. Manage Customers permission box to be checked.

**Comment by jacobuslee** [comment]
I granted permission in Configuration -> Access Control List. 
However, I still get 403 Error.

The detailed error message is
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. Fail() was explicitly called.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[13]
      AuthenticationScheme: Bearer was forbidden.

Does anyone have any solution?

**Comment by jacobuslee** [comment]
I found the solution. Thanks

**Comment by D3bo** [comment]
Closed as not relevant anymore. Anyway probably the user was not granted the Api-User role.
