### ISSUE TITLE
Redirecting to page-not-found

### ISSUE THREAD

**Issue by vyas-hardik** [stepanbenes/api-for-nopcommerce#62]
Hello,

I was getting the same error as Issue #17  . 

Then I added AppId and AppSecret in FacebookAuthenticationRegistrar.cs, which resolved that error but still not getting swagger page. Instead when I hit https://localhost:44369/api it is redirecting me to https://localhost:44369/page-not-found

**Comment by vyas-hardik** [comment]
By mistake

**Comment by anmolrathod** [comment]
I am facing the same issue. Please help me out what change needs to be done to fix this.

@vyas-hardik
