### ISSUE TITLE
OAuth2?

### ISSUE THREAD

**Issue by ctran-espressomoon** [stepanbenes/api-for-nopcommerce#65]
Hi, 
I found in the Sample Application for the original repository (https://github.com/SevenSpikes/nopCommerce-Api-SampleApplication) that it might support OAuth2 Authentication with places to define ClientID, ClientSecret, Authorize Endpoint... 

However, I didn't see that in this repository. Please let me know how to do that?

Thanks,

**Comment by D3bo** [comment]
The original repository was using Identity Server, that was free to use.
As the time being it is a commercial product and it cannot be used for this project.
