### ISSUE TITLE
POST/Customer not working

### ISSUE THREAD

**Issue by rayl999** [stepanbenes/api-for-nopcommerce#70]
hi,
I am trying to use 

### Create a new customer record  
POST /api/customers  

with this data 
```json
{
  "customer": {
    "first_name": "Steve",
    "last_name": "Gates",
    "email": "steve.gates@example.com",
    "role_ids": [ 3 ]   
  }
}
```

But i am getting 

![image](https://user-images.githubusercontent.com/55458276/176415796-c5a43932-ff07-4ba5-bd91-acb1c9c719bc.png)

it is supposed to work as the documentation says but for me its not

**Comment by alymohamedhassan** [comment]
Hey,

How did you fix it?

Also, I have a problem with the response being Forbidden 403, with a guest token.

I have a problem creating a customer account with password using the API.

Thank you :)

**Comment by alymohamedhassan** [comment]
Solved!
And I solved your issue too.

Just add the password parameter in the POST request.

**Comment by Tahateber95** [comment]
@alymohamedhassan Hi 

Could please tell me how did solve the 403 problem ?

Thank you

**Comment by alymohamedhassan** [comment]
> @alymohamedhassan Hi 
> 
> Could please tell me how did solve the 403 problem ?
> 
> Thank you 

Check your access control list from nopcommerce
