### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by alymohamedhassan** [stepanbenes/api-for-nopcommerce#71]
Whenever I try the Swagger tool, I get unauthorized 401

 I don't know where to add or generate an api key

My Nopcommerce version: 4.50

The API version is 4.3

Thank you

**Comment by alymohamedhassan** [comment]
Let me leave this answer here for whoever comes next.

Just generate a new token from the /token below.

I usually name the endpoint login or auth, but didn't expect it would be /token.

Then, take the value inside access_token and go up again and authorize with "Bearer {INSERT_TOKEN_HERE}", without the quotes ofc

**Comment by lianjieYao** [comment]
I tried your method, but this /token does not exist, how should I deal with this problem?
![image](https://user-images.githubusercontent.com/119826170/217979446-b9dbba30-cebe-4ea7-8a61-dbb5a15fff66.png)


> Let me leave this answer here for whoever comes next.
> 
> Just generate a new token from the /token below.
> 
> I usually name the endpoint login or auth, but didn't expect it would be /token.
> 
> Then, take the value inside access_token and go up again and authorize with "Bearer {INSERT_TOKEN_HERE}", without the quotes ofc

**Comment by Faarhad** [comment]
same problem here
