### ISSUE TITLE
NopCustomerDefaults Class Doesn't Have Required Properties

### ISSUE THREAD

**Issue by mucahitaydinlik** [stepanbenes/api-for-nopcommerce#72]
Hello,

I am trying to build the api plugin project but Nop.Core.Domain.Customers -> NopCustomerDefaults class does not have below properties those are required:

FirstNameAttribute
LastNameAttribute
LanguageIdAttribute
CurrencyIdAttribute
DateOfBirthAttribute
GenderAttribute
VatNumberAttribute
VatNumberStatusIdAttribute
CompanyAttribute

![nopcommerce_nopcustomer_defaults_err](https://user-images.githubusercontent.com/32965086/183248289-9f0c1377-469f-4840-9ffe-bab9301303ec.PNG)

How can I handle this problem?

Thanks.

**Comment by amotalles** [comment]
same issue

**Comment by D3bo** [comment]
Fixed with branches 4.7 and develop
