### ISSUE TITLE
API is not working for nopCommerce 4.50.3 .NET 6.0.7

### ISSUE THREAD

**Issue by GaraninR** [stepanbenes/api-for-nopcommerce#76]
I'm trying to get orders data via route /api/orders (GET) and I get a response "401 | Error: Unauthorized"

**Environment:**
![msedge_Br0FKiiefI](https://user-images.githubusercontent.com/2360079/183640027-ac6bfb6f-72f9-4762-8870-58d8aef9bf57.png)

I have a valid and active user admin@localnetwork.by with password '123456':
![msedge_jcCs0LGJgM](https://user-images.githubusercontent.com/2360079/183640200-9bbf38c0-730f-4f10-a036-2daed4d538b9.png)

**Step 1:**
I successfully get a token via /token route:

![msedge_OF6tC9gWSt](https://user-images.githubusercontent.com/2360079/183638727-8f9d2b7d-9615-49bd-96aa-a2c6e7359146.png)

![msedge_VVkZ5401rp](https://user-images.githubusercontent.com/2360079/183638864-726103be-4d4a-4a0c-8645-f3a0bf69b30f.png)

**Step 2:**
I set the token to Swagger for access to the rest of api:

![msedge_XxDxnkgrXp](https://user-images.githubusercontent.com/2360079/183640371-2d08c466-7cba-457c-abf7-63c919e68c75.png) { width:200px; }

![msedge_fUHTaQkGbR](https://user-images.githubusercontent.com/2360079/183640369-675f04a8-7a49-4649-a2db-5fa7995047eb.png) { width:200px; }

**Step 3:**
Then I try to execute a request to the route /api/orders:

![msedge_CmvlQ6cwz5](https://user-images.githubusercontent.com/2360079/183640733-d5958b4b-bd4e-479b-b0f3-0069d92f6c5b.png)

If I get it right I would get a list of orders.

Maybe I did anything wrong?

The rest of the routes of API is not working too. They return the same: Unauthorized.

**Comment by alymohamedhassan** [comment]
Bearer <insert token here>

**Comment by GaraninR** [comment]
Unfortunately, the same error

![VirtualBoxVM_WL4JbIrE8C](https://user-images.githubusercontent.com/2360079/183703089-f8216b3e-da54-4159-ad76-6a4b25af16f2.png)

**Comment by GaraninR** [comment]
I'm sorry. I've found my mistake: I didn't set the API user role for my user
Everything works properly.
I close this issue
