### ISSUE TITLE
Implement controller to manage Warehouses

### ISSUE THREAD

**Issue by D3bo** [stepanbenes/api-for-nopcommerce#77]
Hi @Partiolainen, I saw that you have implemented some specific controllers for warehouse management. I have tested your changes and they work perfectly. Maybe you could do a PR? I don't want to take credit for your work but otherwise I would do it because I would need exactly what you did.

**Comment by Partiolainen** [comment]
@D3bo, you can take whatever you need from my branch without any reference to me

**Comment by D3bo** [comment]
Ok thank you.
