### ISSUE TITLE
23 Issues found when build with nop develop branch

### ISSUE THREAD

**Issue by dheerajshuk** [stepanbenes/api-for-nopcommerce#82]
![image](https://user-images.githubusercontent.com/6016722/201974882-c850fe6c-1f25-49e7-b1df-c0017a8f8383.png)

**Comment by BlagoCuljak** [comment]
Did you manage to find out solution for these errors?

**Comment by D3bo** [comment]
This project is not yet compatible with NopCommerce 4.6.

You should use version 4.5 ([here](https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.50.4)).

**Comment by D3bo** [comment]
#85

**Comment by D3bo** [comment]
Closing because .net7 used by nop 4.60 is out of support.

Fixed in the branch 4.70
