### ISSUE TITLE
api Build with 4 errors

### ISSUE THREAD

**Issue by ora19982022** [stepanbenes/api-for-nopcommerce#84]
1. api Build with 4 errors.
2. this api is based on .Net 5.0, so the errors  mainly said different .Net version.

so this api is not for NopCommerce 4.5? since I am using NopCommerce 4.5

**Comment by D3bo** [comment]
This API is based on .net 6.0  (#56) and is fully compatible with NopCommerce 4.5.
I'm using this project on multiple sites right now. 

Which branch are you using?

**Comment by ora19982022** [comment]
I cannot build it with Visual Studio 2022(both 17.4.3 and 17.5.0), not sure if the VS version issue?

**Comment by ora19982022** [comment]
I am using Main branch, fyi.

**Comment by ora19982022** [comment]
I follow the installation notes, #1/#2/#3 have no problem. but I still cannot build api succecssfully and blocked at #4

This is my folder structure.
![NopMobileFolderStructure](https://user-images.githubusercontent.com/99751041/211458504-5c3306f4-d990-4610-8f93-57a9fe1a0b94.PNG)
This is my total folde structure:
    D:\Projects\nopCommerce
I put both NopCommerce and API in this folder:
    D:\Projects\nopCommerce\NopCommerce
    D:\Projects\nopCommerce\api-for-nopcommerce


This is the structure of NopCommerce.
![NopStructure](https://user-images.githubusercontent.com/99751041/211458777-afed1a27-da86-42bd-9f61-d0f04c0a73f2.PNG)

This is the structure of api-for-nopcommerce.
![ApiStructure](https://user-images.githubusercontent.com/99751041/211458830-4aed336e-e648-489c-bec3-372ae50bec0b.PNG)

I can build Nopcommerce without problem, but I got errors when I built Api, the errors message is as following:

Errors cannot find the project information “D:\Projects\nopCommerce\nopCommerce\src\Libraries\Nop.Core\Nop.Core.csproj”
Errors cannot find the project information “D:\Projects\nopCommerce\nopCommerce\src\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj”

but I can see above files in the corresponding folders. any idea? thanks in advance.

My Visual Studio is version 2022.
I also saw the .net version issue in errors message like:
target framework "net5.0" is not supported, wont have security update in the future etc..
“D:\Projects\nopCommerce\nopCommerce\src\Libraries\Nop.Core\Nop.Core.csproj” points to "net7.0" etc..

**Comment by ora19982022** [comment]
Fixed the problem, since the .net version is different, NopCommerce 4.5 is using .net sdk verison 6, api is still using .net sdk version 5. fyi.

**Comment by D3bo** [comment]
As you can see in the [project file](https://github.com/stepanbenes/api-for-nopcommerce/blob/main/Nop.Plugin.Api/Nop.Plugin.Api.csproj) the API is using the .net version 6.

@stepanbenes am I missing something?

**Comment by stepanbenes** [comment]
@D3bo You are correct. We are using .NET 6. I misread the comment.

**Comment by D3bo** [comment]
> 
Indeed I was pretty sure #56  😄 

btw we should update the readme.

**Comment by stepanbenes** [comment]
In the readme there is a reference to `ClientApp` that still uses .NET 5...

**Comment by ora19982022** [comment]
api is still using version 5, that's why build will run into errors. I downloaded NopCommerce V4.50.0 and fixed the problem, they need to keep the same version.

**Comment by ora19982022** [comment]
> Fixed the problem, since the .net version is different, NopCommerce 4.5 is using .net sdk verison 6, api is still using .net sdk version 5. fyi.

I downloaded NopCommerce V4.50.0 and fixed the problem. fyi.

**Comment by VFCoder** [comment]
> > Fixed the problem, since the .net version is different, NopCommerce 4.5 is using .net sdk verison 6, api is still using .net sdk version 5. fyi.
> 
> I downloaded NopCommerce V4.50.0 and fixed the problem. fyi.

I'm having the same issue. What did you do exactly to fix it?

**Comment by VFCoder** [comment]
Fixed the issue by adding the Framework project to the api solution

**Comment by D3bo** [comment]
Closing, the problem were the use of the wrong version of nopCommerce
