### ISSUE TITLE
do you have any plan for 4.60

### ISSUE THREAD

**Issue by phungxuanvuong97** [stepanbenes/api-for-nopcommerce#85]
Do you have any plan for lastest version?

**Comment by VFCoder** [comment]
I support this! 4.6 has made some nice improvements and 4.5's api isn't compatible in various ways.

**Comment by stepanbenes** [comment]
Yes, that would be nice. Unfortunately, Currently, I don't have capacity for this. PRs are welcome.

**Comment by syky27** [comment]
PRs, are welcome, yet there are 2 PRs, for over half a year, that did not even got a response... This repo is dead...

**Comment by onestar1** [comment]
I guess the author hasn't continued to update it for the time being
