### ISSUE TITLE
Nop4.6 doesn't work with this API version, right?

### ISSUE THREAD

**Issue by onestar1** [stepanbenes/api-for-nopcommerce#89]
Look at nop4.5 after upgrading to 4.6 There are big changes, I don't know if anyone is using the nop4.6 version

**Comment by hiepns97it** [comment]
Yes. I have successfully integrated v.4.6 into the api.

**Comment by stepanbenes** [comment]
> Yes. I have successfully integrated v.4.6 into the api. Took 1 day of my work to fix it

Nice. You can make a pull request.

**Comment by syky27** [comment]
> > Yes. I have successfully integrated v.4.6 into the api. Took 1 day of my work to fix it
> 
> Nice. You can make a pull request.

Why bother when there are PR's opened since 2022 without getting even a reply....?

**Comment by stepanbenes** [comment]
> > > Yes. I have successfully integrated v.4.6 into the api. Took 1 day of my work to fix it
> > 
> > 
> > Nice. You can make a pull request.
> 
> Why bother when there are PR's opened since 2022 without getting even a reply....?

You are right. My reaction time in this repo is a little bit slow. Do you want to take ownership?

**Comment by syky27** [comment]
> > > > Yes. I have successfully integrated v.4.6 into the api. Took 1 day of my work to fix it
> > > 
> > > 
> > > Nice. You can make a pull request.
> > 
> > 
> > Why bother when there are PR's opened since 2022 without getting even a reply....?
> 
> You are right. My reaction time in this repo is a little bit slow. Do you want to take ownership?

Hmmm... Let me think about that... Potentially yes, but I need to be sure that I could give it the time it needs...

**Comment by stepanbenes** [comment]
> > > > > Yes. I have successfully integrated v.4.6 into the api. Took 1 day of my work to fix it
> > > > 
> > > > 
> > > > Nice. You can make a pull request.
> > > 
> > > 
> > > Why bother when there are PR's opened since 2022 without getting even a reply....?
> > 
> > 
> > You are right. My reaction time in this repo is a little bit slow. Do you want to take ownership?
> 
> Hmmm... Let me think about that... Potentially yes, but I need to be sure that I could give it the time it needs...

I am not using this project in my daily work as I was two years ago, so I don't have the necessary focus and time for this. This project needs someone that is also actively using nopcommerce and its api.

**Comment by syky27** [comment]
I am using few instances of nopCommerce daily, so yes I can keep up with updates of nopCommerce. However maintaining OS projects takes a lot of extra time than just maintaining something for internal use... So I need to think about it, if I want and can make such a commitment...

**Comment by D3bo** [comment]
I am using nopcommerce daily and I'd like to maintain this project if you
want.



Il lun 4 mar 2024, 10:59 Tomas Sykora, jr. ***@***.***> ha
scritto:

**Comment by stepanbenes** [comment]
@D3bo Great! Thank you. I have given you access. Feel free to do any changes.

**Comment by stepanbenes** [comment]
> I am using few instances of nopCommerce daily, so yes I can keep up with updates of nopCommerce. However maintaining OS projects takes a lot of extra time than just maintaining something for internal use... So I need to think about it, if I want and can make such a commitment...

I understand, it is a large commitment to manage the whole project alone, but I can make you also a collaborator as @D3bo if you want to be more involved in the project.

**Comment by stepanbenes** [comment]
@onestar1 Sorry for hijacking the issue.

**Comment by VFCoder** [comment]
> Yes. I have successfully integrated v.4.6 into the api. Took 1 day of my work to fix it

Can you post it please?

**Comment by VFCoder** [comment]
@hiepns97it can you pull your updated version 4.6 api plugin please?
